<?php
use Underscore\Underscore as _;

$project        = $this->project;
$product        = $this->product;
$groups         = $this->groups;
$headquarters   = $this->headquarters;

$finalProduct = $product->finalProduct;

//$project = new Project();
//$product = new Product;

?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Proyectos</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/project">Proyectos</a></li>
                        <li><a href="/project/<?= $project->getProjectId() ?>/academic-calendar/<?= $project->getACproposalId() ?>">Edición de Propuesta de Calendario Académico</a></li>
                        <li class="active">Propuesta de Estructura de Producto</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <!--dropdown select-->
            <a class='dropdown-button btn' data-activates='dropdown-select'>Grupos</a>
            <?= $this->partial(__PATH__ . "/app/view/project/partials/proposal-product-structure-dropdown.phtml"); ?>
            <!--end dropdown select-->
            <div class="card-panel">
                <h4 class="header2">Gestión de Grupos</h4>
                <p class="caption">Grupos que comprende el producto</p>
                <div class="row">
                    <div class="col s12">
                        <a class='dropdown-button btn' data-activates='dropdown-action'>Acciones</a>
                        <ul id='dropdown-action' class='dropdown-content'>
<!--                            <li>
                                <a href="enable">Activar</a>
                            </li>
                            <li>
                                <a href="disable">Desactivar</a>
                            </li>-->
                            <li>
                                <a href="delete">Eliminar</a>
                            </li>
                        </ul>
                        <a class="btn cyan waves-effect waves-light" href="group/create">Añadir Grupo</a>
                    </div>
                </div>
                <div class="row">
                    <div class="col s12">
                        <table id="group-table" class="responsive-table display" cellspacing="0">
                            <thead>
                                <tr>
                                    <th></th>
                                    <th>N°</th>
                                    <th>Descripción</th>
                                    <th>Sede</th>
                                    <th>Fecha de Inicio</th>
                                    <th>Fecha Final</th>
                                    <th>Opciones</th>
                                </tr>
                            </thead>
                            <tfoot>
                                <tr>
                                    <th></th>
                                    <th>N°</th>
                                    <th>Descripción</th>
                                    <th>Sede</th>
                                    <th>Fecha de Inicio</th>
                                    <th>Fecha Final</th>
                                    <th>Opciones</th>
                                </tr>
                            </tfoot>
                            <tbody>
                            <?php
                            if($groups){
                                $enumerator = 0;
                                
                                _::each($groups, function(Group $group) use (&$enumerator, $headquarters){
                                    $enumerator = ++$enumerator;
                                    $headquarter = $headquarters[$group->getHeadquarterId()];
//                                    $headquarter = new Headquarter;
                                    
                                    ?>
                                    <tr data-id="<?= $group->getGroupId() ?>">
                                        <td>
                                            <?php
                                            if($group->getTypeEntry() !== Group::TYPE_ENTRY_BY_DEFULT){
                                                ?>
                                                <input type="checkbox" class="browser-default" value="<?= $group->getGroupId() ?>">
                                                <?php
                                            }
                                            ?>
                                        </td>
                                        <td><?= $enumerator ?></td>
                                        <td><?= $group->getDescription() ?></td>
                                        <td><?= $headquarter->getDescription() ?></td>
                                        <td><?= $group->getStarDate() ?></td>
                                        <td><?= $group->getFinalDate() ?></td>
                                        <td>
                                            <a class="waves-effect waves-light btn" href="#">Editar</a>
                                        </td>
                                    </tr>
                                    <?php
                                });
                            }else{
                                ?>
                                <tr>
                                    <td colspan="7">No hay grupos configurados</td>
                                </tr>
                                <?php
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <script>
                $(document).ready(function(){
                    $("#dropdown-action li a").click(function(e){
                        e.preventDefault();
                        
                        var selectedGroupIds = [];
                                
                        $("#group-table input[type=checkbox]:checked").each(function(){
                            selectedGroupIds.push($(this).val());
                        });
                        
                        if(!selectedGroupIds.length){
                            return;
                        }
                        
                        var href = $(this).attr("href");
                        
                        $.ajax({
                            url     : "/project/<?= $project->getProjectId() ?>/product-structure/<?= $project->getStoreId() ?>/group/action",
                            method  : "POST",
                            data    : { 
                                action      : href,
                                groupIds    : selectedGroupIds
                            },
                            dataType: "json"
                        })
                        .done(function(response){
                            console.log(response);
                            if (response.success){
                                window.location.reload();
                            } else {
                                window.Materialize.toast(response.message, 3000);
                            }
                        })
                        .fail(function(response){
                            console.log(response.responseText);
                        });
                    });
                });
            </script>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->