<?php
use Underscore\Underscore as _;

$project = $this->project;
$product = $this->product;
$headquarters = $this->headquarters;

$finalProduct = $product->finalProduct;

//$project = new Project();
//$product = new Product;

?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Proyectos</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/project">Proyectos</a></li>
                        <li><a href="/project/<?= $project->getProjectId() ?>/academic-calendar/<?= $project->getACproposalId() ?>">Edición de Propuesta de Calendario Académico</a></li>
                        <li class="active">Propuesta de Estructura de Producto</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <div class="card-panel">
                <p class="caption">Crear Grupo</p>
                <div class="row">
                    <form class="col s12" method="post" 
                          action="/project/<?= $project->getProjectId() ?>/product-structure/<?= $project->getStoreId() ?>/group/create"
                          name="group-form">
                        <div class="row">
                            <div class="input-field col s6">
                                <textarea id="description" class="materialize-textarea" name="description"></textarea>
                                <label for="description" >Descripción</label>
                            </div>
                            <div class="input-field col s6">
                                <select name="headquarter-id">
                                    <?php
                                    _::each($headquarters, function(Headquarter $headquarter) {
                                        ?>
                                        <option value="<?= $headquarter->getHeadquarterId() ?>"><?= substr_with_dots($headquarter->getDescription(), 40) ?></option>
                                        <?php
                                    });
                                    ?>
                                </select>
                                <label>Sede</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <input type="date" class="datepicker" name="start-date">
                                <label>Fecha de Inicio</label>
                            </div>
                            <div class="input-field col s6">
                                <input type="date" class="datepicker" name="final-date">
                                <label>Fecha Final</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <button class="btn cyan waves-effect waves-light right" type="submit"> Registrar
                                    <i class="mdi-content-send right"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <script>
                $(document).ready(function(){
                    /*
                     * Form
                     */
                    $("form[name=group-form]").send(function (response) {
                        console.log(response);
                        if (response.success){
                            window.Materialize.toast("Se guardaron los datos correctamente", 3000, "", function(){
                                window.location = response.URIredirect;
                            });
                        } else {
                            window.Materialize.toast(response.message, 3000);
                        }
                    }, "json");
                });
            </script>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->