<?php
use Underscore\Underscore as _;

$project = $this->project;
$product = $this->product;

$finalProduct = $product->finalProduct;

//$project = new Project();
//$product = new Product;

?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Proyectos</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/project">Proyectos</a></li>
                        <li><a href="/project/<?= $project->getProjectId() ?>/academic-calendar/<?= $project->getACproposalId() ?>">Edición de Propuesta de Calendario Académico</a></li>
                        <li class="active">Propuesta de Estructura de Producto</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <div class="card-panel">
                <p class="caption">Crear Unidad</p>
                <div class="row">
                    <form class="col s12" method="post" 
                          action="create-unity"
                          name="unity-form">
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="name" type="text" name="name">
                                <label for="name">Nombre</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <textarea id="description" class="materialize-textarea" name="description"></textarea>
                                <label for="description" >Descripción</label>
                            </div>
                            <div class="col s6 input-field">
                                <label>Fecha de Disponibilidad</label>
                                <br>
                                <br>
                                <div class="row">
                                    <div class="input-field col s6">
                                        <input type="date" class="datepicker" name="availability-start-date">
                                        <label>De</label>
                                    </div>
                                    <div class="input-field col s6">
                                        <input type="date" class="datepicker" name="availability-final-date">
                                        <label>Hasta</label>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s6">
                                <select name="position">
                                    <option value="1">1</option>
                                </select>
                                <label>Posición</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <button class="btn cyan waves-effect waves-light right" type="submit"> Registrar
                                    <i class="mdi-content-send right"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <script>
                $(document).ready(function(){
                    /*
                     * Form
                     */
                    $("form[name=unity-form]").send(function (response) {
                        console.log(response);
                        if (response.success){
                            window.Materialize.toast("Se guardaron los datos correctamente", 3000, "", function(){
                                window.location = response.URIredirect;
                            });
                        } else {
                            window.Materialize.toast(response.message, 3000);
                        }
                    }, "json");
                });
            </script>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->