<?php
$country = $this->country;
?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Países</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/localization/country">Países</a></li>
                        <li class="active">Ver País</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <div class="row">
                <div class="col s12 m12 l6">
                    <div class="card-panel">
                        <div class="row">
                            <form class="col s12" method="post" action="/localization/country/<?= $country->getId() ?>">
                                <div class="row">
                                    <div class="input-field col s12">
                                        <input id="country-name" type="text" name="country-name" value="<?= $country->getName() ?>">
                                        <label for="country-name">Nombre de País</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <input id="country-postal-code" type="text" name="country-postal-code" value="<?= $country->getPostalCode() ?>">
                                        <label for="country-postal-code">Código Postal</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <button class="btn cyan waves-effect waves-light right" type="submit"> Actualizar
                                            <i class="mdi-content-send right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->