<?php
use Underscore\Underscore as _;

$departament    = $this->departament;
$countries      = $this->countries;
?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Departamentos</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/localization/departament">Departamentos</a></li>
                        <li class="active">Ver Departamento</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <div class="row">
                <div class="col s12 m12 l6">
                    <div class="card-panel">
                        <div class="row">
                            <form class="col s12" method="post" action="/localization/departament/<?= $departament->getId() ?>">
                                <div class="row">
                                    <div class="input-field col s12">
                                        <select name="departament-country">
                                            <?php
                                            if($countries){
                                                ?>
                                                <option value="<?= $departament->getCountryId() ?>"><?= $countries[$departament->getCountryId()]->getName() ?></option>    
                                                <?php
                                                _::each($countries, function(Country $country) use ($departament){
                                                    if($departament->getCountryId() !== $country->getId()){
                                                        ?>
                                                        <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                                        <?php
                                                    }
                                                });
                                            }
                                            ?>
                                        </select>
                                        <label>Pais</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <input id="departament-name" type="text" name="departament-name" value="<?= $departament->getName() ?>">
                                        <label for="departament-name">Nombre de Departamento</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <button class="btn cyan waves-effect waves-light right" type="submit"> Actualizar
                                            <i class="mdi-content-send right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->