<?php
use Underscore\Underscore as _;

$districts = $this->districts;
$provinces = $this->provinces;
$departaments = $this->departaments;
$countries = $this->countries;
?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Distritos</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/localization/district">Distritos</a></li>
                        <li class="active">Lista de Distritos</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">

            <div class="row">
                <div class="col s12">
                    <a class="waves-effect waves-light btn" href="/localization/district/create">Crear Distrito</a>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col s12">
                    <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Provincia</th>
                                <th>Departamento</th>
                                <th>País</th>
                                <th>Opción</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Provincia</th>
                                <th>Departamento</th>
                                <th>País</th>
                                <th>Opción</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        <?php
                        if($districts){
                            _::each($districts, function(District $district) use ($provinces, $departaments, $countries){
                                $province = $provinces[$district->getProvinceId()];
                                $departament = $departaments[$province->getDepartamentId()];
                                $country = $countries[$departament->getCountryId()];
                                
                                ?>
                                <tr>
                                    <td><?= $district->getId() ?></td>
                                    <td><?= $district->getName() ?></td>
                                    <td><?= $province->getName() ?></td>
                                    <td><?= $departament->getName() ?></td>
                                    <td><?= $country->getName() ?></td>
                                    <td>
                                        <a class="waves-effect waves-light btn" href="/localization/district/<?= $district->getId() ?>">Ver</a>
                                    </td>
                                </tr>
                                <?php
                            });
                        }else{
                            ?>
                            <tr>
                                <td colspan="5">No hay distritos</td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <script>
                $(document).ready(function () {

                });
            </script>

        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->