<?php
use Underscore\Underscore as _;

$headquarter            = $this->headquarter;
//$headquarter = new Headquarter;
$headquarterDistrict    = $this->headquarterDistrict;
$headquarterProvince    = $this->headquarterProvince;
$headquarterDepartament = $this->headquarterDepartament;
$districts              = $this->districts;
$provinces              = $this->provinces;
$departaments           = $this->departaments;
$countries              = $this->countries;
?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Sedes</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/localization/headquarter">Sedes</a></li>
                        <li class="active">Ver Sede</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <div class="row">
                <div class="col s12 m12 l6">
                    <div class="card-panel">
                        <div class="row">
                            <form class="col s12" method="post" action="/localization/headquarter/<?= $headquarter->getHeadquarterId() ?>" name="headquarter-form">
                                <div class="row">
                                    <div class="input-field col s12">
                                        <select name="country-id" data-action="/localization/json/departament-of-country" data-target="departament-id">
                                            <option value="<?= $headquarterDepartament->getCountryId() ?>"><?= $countries[$headquarterDepartament->getCountryId()]->getName() ?></option>
                                            <?php
                                            _::each($countries, function(Country $country) use ($headquarterDepartament){
                                                if($headquarterDepartament->getCountryId() !== $country->getId()){
                                                    ?>
                                                    <option value="<?= $country->getId() ?>"><?= $country->getName() ?></option>
                                                    <?php
                                                }
                                            });
                                            ?>
                                        </select>
                                        <label>Pais</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <select name="departament-id" data-action="/localization/json/province-of-departament" data-target="province-id">
                                            <option value="<?= $headquarterDepartament->getId() ?>"><?= $headquarterDepartament->getName() ?></option>
                                            <?php
                                            _::each($departaments, function(Departament $departament) use ($headquarterDepartament){
                                                if($headquarterDepartament->getId() !== $departament->getId()){
                                                    ?>
                                                    <option value="<?= $departament->getId() ?>"><?= $departament->getName() ?></option>
                                                    <?php
                                                }
                                            });
                                            ?>
                                        </select>
                                        <label>Departamento</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <select name="province-id" data-action="/localization/json/district-of-province" data-target="headquarter-district-id">
                                            <option value="<?= $headquarterProvince->getId() ?>"><?= $headquarterProvince->getName() ?></option>    
                                            <?php
                                            _::each($provinces, function(Province $province) use ($headquarterProvince){
                                                if($headquarterProvince->getId() !== $province->getId()){
                                                    ?>
                                                    <option value="<?= $province->getId() ?>"><?= $province->getName() ?></option>
                                                    <?php
                                                }
                                            });
                                            ?>
                                        </select>
                                        <label>Provincia</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <select name="headquarter-district-id">
                                            <option value="<?= $headquarterDistrict->getId() ?>"><?= $headquarterDistrict->getName() ?></option>    
                                            <?php
                                            _::each($districts, function(District $district) use ($headquarterDistrict){
                                                if($headquarterDistrict->getId() !== $district->getId()){
                                                    ?>
                                                    <option value="<?= $district->getId() ?>"><?= $district->getName() ?></option>
                                                    <?php
                                                }
                                            });
                                            ?>
                                        </select>
                                        <label>Distrito</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <textarea id="headquarter-description" class="materialize-textarea" name="headquarter-description"><?= $headquarter->getDescription() ?></textarea>
                                        <label for="headquarter-description" >Descripción</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <input id="headquarter-address" type="text" name="headquarter-address" value="<?= $headquarter->getAddress() ?>">
                                        <label for="headquarter-address">Dirección</label>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="input-field col s12">
                                        <button class="btn cyan waves-effect waves-light right" type="submit"> Actualizar
                                            <i class="mdi-content-send right"></i>
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                $(document).ready(function(){
                    $("form[name=headquarter-form]").chainSelects("auto");
                });
            </script>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->