<?php
use Underscore\Underscore as _;

$sales       = $this->sales;
$filterSaleIds = $this->filterSaleIds;
?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <div class="container">
            <div class="row">
                <div class="col s12">
                    <h5 class="breadcrumbs-title">Buscar Venta</h5>
                    <br>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">

            <div class="row">
                <div class="col s12">
                    <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Estado</th>
                                <th>Fecha de Emisión</th>
                                <th>Tipo de Moneda</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Código</th>
                                <th>Estado</th>
                                <th>Fecha de Emisión</th>
                                <th>Tipo de Moneda</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        <?php
                        if($sales){
                            _::each($sales, function(Sale $sale) use ($filterSaleIds){
                                if($filterSaleIds && in_array($sale->getSaleId(), $filterSaleIds)){
                                    return;
                                }
                                
                                ?>
                                <tr>
                                    <td><?= $sale->getSaleId() ?></td>
                                    <td><?= $sale->getStatus() ?></td>
                                    <td><?= $sale->getEmissionDate() ?></td>
                                    <td><?= $sale->getTypeCoin() ?></td>
                                    <td>
                                        <a class="waves-effect waves-light btn"
                                           data-text="<?= $sale->getSaleId() ?>"
                                           data-value="<?= $sale->getSaleId() ?>">Seleccionar</a>
                                    </td>
                                </tr>
                                <?php
                            });
                        }else{
                            ?>
                            <tr>
                                <td colspan="5">No hay Ventas</td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <script>
                $(document).ready(function () {
                    $("a[data-value][data-text]").click(function(){
                        if(window.opener){
                            $(window.opener.document).find("[searcher-sale-target-text]").val($(this).attr("data-text"));
                            $(window.opener.document).find("[searcher-sale-target-value]").val($(this).attr("data-value"));
                            
                            window.close();
                        }
                    });
                });
            </script>

        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->