<!DOCTYPE html>
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
        <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
        <title><?= $this->pageTitle ?></title>
        <!-- Favicons-->
        <link rel="icon" href="images/favicon/favicon-32x32.png" sizes="32x32">
        <!-- Favicons-->
        <link rel="apple-touch-icon-precomposed" href="images/favicon/apple-touch-icon-152x152.png">
        <!-- For iPhone -->
        <meta name="msapplication-TileColor" content="#00bcd4">
        <meta name="msapplication-TileImage" content="images/favicon/mstile-144x144.png">
        <!-- For Windows Phone -->
        <!-- CORE CSS-->
        <link href="/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="/css/style.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- Custome CSS-->    
        <link href="/css/custom/custom.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="/css/layouts/page-center.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
        <link href="/js/vendor/plugins/prism/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="/js/vendor/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- jQuery Library -->
        <script type="text/javascript" src="/js/vendor/plugins/jquery-1.11.2.min.js"></script>
    </head>
    <body class="grey">
        <!-- Start Page Loading -->
        <div id="loader-wrapper">
            <div id="loader"></div>        
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>
        <!-- End Page Loading -->
        
        <div id="login-page" class="row">
            <div class="col s12 z-depth-4 card-panel">
                <form class="login-form" action="/login" id="login-form">
                    <div class="row">
                        <div class="input-field col s12 center">
                            <img src="/resources/image/login-logo.png" alt="" class="circle responsive-img valign profile-image-login">
                            <p class="center login-form-text">
                                Plataforma de OWL Editorial
                            </p>
                        </div>
                    </div>
                    <div class="row margin">
                        <div class="input-field col s12">
                            <i class="mdi-social-person-outline prefix"></i>
                            <input id="user-email" type="text" name="user-email">
                            <label for="user-email" class="center-align">Email</label>
                        </div>
                    </div>
                    <div class="row margin">
                        <div class="input-field col s12">
                            <i class="mdi-action-lock-outline prefix"></i>
                            <input id="user-password" type="password" name="user-password">
                            <label for="user-password">Contraseña</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m12 l12  login-text">
                            <input type="checkbox" id="remember-me" />
                            <label for="remember-me">Recordar contraseña</label>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12">
                            <button class="btn waves-effect waves-light col s12" type="submit">Ingresar</button>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input-field col s12 m12 l12">
                            <p class="margin right-align medium-small">
                                <a href="/login/forgot-password">¿Olvidaste tu contraseña?</a>
                            </p>
                        </div>          
                    </div>

                </form>
            </div>
        </div>
        <script>
            $(document).ready(function(){
                $("#login-form").send(function(success){
                    if(success){
                        window.location = "/login/forwarder";
                    }else{
                        window.Materialize.toast("El usuario y/o contraseña son incorrectos", 3000);
                    }
                }, "json");
            });
        </script>
        
        <!-- ================================================
          Scripts
          ================================================ -->
        <!--materialize js-->
        <script type="text/javascript" src="/js/vendor/materialize.min.js"></script>
        <!--prism-->
        <script type="text/javascript" src="/js/vendor/plugins/prism/prism.js"></script>
        <!--scrollbar-->
        <script type="text/javascript" src="/js/vendor/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>

        <!--plugins.js - Some Specific JS codes for Plugin Settings-->
        <script type="text/javascript" src="/js/vendor/plugins.min.js"></script>
        <!--custom-script.js - Add your own theme custom JS-->
        <script type="text/javascript" src="/js/vendor/custom-script.js"></script>
    </body>
</html>