<?php
use Underscore\Underscore as _;

$categories  = $this->categories;
?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Administración</h5>
                    <ol class="breadcrumbs">
                        <li><a href="/administration/category">Categorías</a></li>
                        <li class="active">Lista de Categorías</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">

            <div class="row">
                <div class="col s12">
                    <a class="waves-effect waves-light btn" href="/administration/category/create">Crear Categoría</a>
                </div>
            </div>
            <br>
            <div class="row">
                <div class="col s12">
                    <table id="data-table-simple" class="responsive-table display" cellspacing="0">
                        <thead>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Descripción</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr>
                                <th>Código</th>
                                <th>Nombre</th>
                                <th>Descripción</th>
                            </tr>
                        </tfoot>
                        <tbody>
                        <?php
                        if($categories){
                            _::each($categories, function(Category $category){
                                ?>
                                <tr>
                                    <td><?= $category->getCategoryId() ?></td>
                                    <td><?= $category->getName() ?></td>
                                    <td><?= substr_with_dots($category->getDescription(), 30) ?></td>
                                    <td>
                                        <a class="waves-effect waves-light btn" href="/administration/category/<?= $category->getCategoryId() ?>">Ver</a>
                                    </td>
                                </tr>
                                <?php
                            });
                        }else{
                            ?>
                            <tr>
                                <td colspan="4">No hay categorías</td>
                            </tr>
                            <?php
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
            <script>
                $(document).ready(function () {

                });
            </script>

        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->