<!-- START FOOTER -->
<footer class="page-footer grey">
    <div class="footer-copyright">
        <div class="container">
            <span>Copyright © 2016 <a class="grey-text text-lighten-4" href="/" target="_blank">AYE Platform</a> Todos los derechos reservados.</span>
            <span class="right"> Desarrollado por <a class="grey-text text-lighten-5" href="#">AYE Solutions</a></span>
        </div>
    </div>
</footer>
<!-- END FOOTER -->