<?php
use Underscore\Underscore as _;

$user = get_user_session();

$constraintProfiles = [
    UserProfile::TYPE_PROFESSOR,
    UserProfile::TYPE_STUDENT,
    UserProfile::TYPE_CLIENT,
];

$userProfiles = array_values($user->userProfiles);
$userProfiles = array_filter($userProfiles, function($userProfile) use ($constraintProfiles){
    return !in_array($userProfile, $constraintProfiles);
});
$profilesTotal = count($userProfiles);

?>
<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color grey">
            <div class="nav-wrapper">
                <ul class="left">                    
                    <li>
                        <h1 class="logo-wrapper">
                            <a href="/dashboard" class="brand-logo darken-1">
                                <img src="/resources/image/materialize-logo.png" alt="materialize logo">
                            </a> 
                            <span class="logo-text">Materialize</span>
                        </h1>
                    </li>
                </ul>
                <div class="header-search-wrapper hide-on-med-and-down">
                    <i class="mdi-action-search"></i>
                    <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma"/>
                </div>
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen"><i class="mdi-action-settings-overscan"></i></a>
                    </li>
                    <li>
                        <a href="javascript:void(0);" class="waves-effect waves-block waves-light notification-button" data-activates="notifications-dropdown">
                            <i class="mdi-action-account-circle"></i>
                        </a>
                    </li>
                </ul>
                <!-- notifications-dropdown -->
                <ul id="notifications-dropdown" class="dropdown-content">
                    <li>
                        <h5>SELECCIONAR PERFIL</h5>
                    </li>
                    <li class="divider"></li>
                    <?php
                    _::each($userProfiles, function($userProfile) use ($user){
                        if($userProfile === $user->activeAdministrationUserProfile){
                            ?>
                            <li>
                                <a href="#">
                                    <i class="mdi-toggle-check-box"></i> <?= $userProfile ?>
                                </a>
                            </li>    
                            <?php 
                        }else{
                           ?>
                            <li>
                                <a href="/login/change-administration-user-profile/<?= $userProfile ?>">
                                    <i class="mdi-toggle-check-box-outline-blank"></i> <?= $userProfile ?>
                                </a>
                            </li>    
                            <?php 
                        }
                    });
                    ?>
                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->