<?php
$units = $this->units;
?>
<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color">
            <div class="nav-wrapper">
                <ul class="left">                    
                    <li>
                        <h1 class="logo-wrapper">
                            <a href="/" class="brand-logo darken-1">
                                <img src="/resources/image/materialize-logo.png" alt="materialize logo">
                            </a> 
                            <span class="logo-text">Materialize</span>
                        </h1>
                    </li>
                </ul>
                <ul class="right hide-on-med-and-down">
                    <li>
                        <a href="javascript:void(0);" class="waves-effect waves-block waves-light toggle-fullscreen">
                            <i class="mdi-action-settings-overscan"></i>
                        </a>
                    </li>
                    <?php
                    if($units){
                        ?>
                        <li>
                            <a href="#" data-activates="chat-out" class="waves-effect waves-block waves-light chat-collapse">
                                <i class="mdi-communication-chat"></i>
                            </a>
                        </li>
                        <?php
                    }
                    ?>
                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->