<?php
    $user = get_user_session();
//    $user = new User();
    $person = $user->person;
    
    if($user->getPersonType() === User::PERSON_TYPE_NATURAL && $person instanceof NaturalPerson){
        $fullName = $person->getName() . " " . $person->getLastName() . " " . $person->getMotherLastName();
    }else if($user->getPersonType() === User::PERSON_TYPE_JURIDICAL && $person instanceof JuridicalPerson){
        $fullName = $person->getTradename();
    }
    
    $fullName = substr_with_dots($fullName, 15);
    
    
    /*
     * Profile presentation string
     */
    $profilePresentationString = ucwords(strtolower(str_replace("_", " ", $user->activeAdministrationUserProfile)));
?>
<!-- START LEFT SIDEBAR NAV-->
<aside id="left-sidebar-nav">
    <ul id="slide-out" class="side-nav fixed leftside-navigation">
        <li class="user-details cyan darken-2">
            <div class="row">
                <div class="col col s4 m4 l4">
                    <img src="/resources/image/avatar.jpg" alt="" class="circle responsive-img valign profile-image">
                </div>
                <div class="col col s8 m8 l8">
                    <ul id="profile-dropdown" class="dropdown-content">
                        <li>
                            <a href="#"><i class="mdi-action-face-unlock"></i> Perfil</a>
                        </li>
                        <li>
                            <a href="#"><i class="mdi-action-settings"></i> Config.</a>
                        </li>
                        <li>
                            <a href="#"><i class="mdi-communication-live-help"></i> Ayuda</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="/login/signout"><i class="mdi-hardware-keyboard-tab"></i> Salir</a>
                        </li>
                    </ul>
                    <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown"><?= $fullName ?><i class="mdi-navigation-arrow-drop-down right"></i></a>
                    <p class="user-roal"><?= substr_with_dots($profilePresentationString, 17) ?></p>
                </div>
            </div>
        </li>
        <li class="bold">
            <a href="/dashboard" class="waves-effect waves-cyan">
                <i class="mdi-action-dashboard"></i> Principal
            </a>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-action-account-box"></i> Usuarios
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/user">Mis usuarios</a>
                            </li>
                            <li>
                                <a href="/user/create">Crear Usuario</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-action-view-carousel"></i> Proyectos
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/project">Mis Proyectos</a>
                            </li>
                            <li>
                                <a href="/project/create">Crear Proyecto</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-action-store"></i> Productos
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/product">Mis Productos</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-maps-place"></i> Localización
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/localization/country">Países</a>
                            </li>
                            <li>
                                <a href="/localization/departament">Departamentos</a>
                            </li>
                            <li>
                                <a href="/localization/province">Provincias</a>
                            </li>
                            <li>
                                <a href="/localization/district">Distritos</a>
                            </li>
                            <li>
                                <a href="/localization/headquarter">Sedes</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-action-extension"></i> Administración
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/administration/category">Categorías</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-action-settings-input-component"></i> Preferencias
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/preference/catalog">Catálogo</a>
                            </li>
                            <li>
                                <a href="/preference/theme">Temas</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="no-padding">
            <ul class="collapsible collapsible-accordion">
                <li class="bold">
                    <a class="collapsible-header waves-effect waves-cyan">
                        <i class="mdi-image-assistant-photo"></i> Soporte
                    </a>
                    <div class="collapsible-body">
                        <ul>
                            <li>
                                <a href="/support">Mis Incidencias</a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>
        </li>
        <li class="li-hover">
            <div class="divider"></div>
        </li>
        <li class="li-hover">
            <p class="ultra-small margin more-text">MÁS</p>
        </li>
        <li>
            <a href="angular-ui.html">
                <i class="mdi-action-verified-user"></i> Mis Emails
            </a>
        </li>
        <li class="li-hover">
            <div class="divider"></div>
        </li>
        <li class="li-hover">
            <p class="ultra-small margin more-text">Ventas diarias</p>
        </li>
        <li class="li-hover">
            <div class="row">
                <div class="col s12 m12 l12">
                    <div class="sample-chart-wrapper">                            
                        <div class="ct-chart ct-golden-section" id="ct2-chart"></div>
                    </div>
                </div>
            </div>
        </li>
    </ul>
    <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
</aside>
<!-- END LEFT SIDEBAR NAV-->