<?php
use Underscore\Underscore as _;

$typesInterest = [
    Interest::TYPE_FIX_CHARGE,
    Interest::TYPE_PERCENT,
];

?>
<!-- START CONTENT -->
<section id="content">
    <!--breadcrumbs start-->
    <div id="breadcrumbs-wrapper">
        <!-- Search for small screen -->
        <div class="header-search-wrapper grey hide-on-large-only">
            <i class="mdi-action-search active"></i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Explorar en la plataforma">
        </div>
        <div class="container">
            <div class="row">
                <div class="col s12 m12 l12">
                    <h5 class="breadcrumbs-title">Producto en almacén</h5>
                    <ol class="breadcrumbs">
                        <li class="active">Crear Interés</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!--breadcrumbs end-->
    <!--start container-->
    <div class="container">
        <div class="section">
            
            <div class="card-panel">
                <div class="row">
                    <form class="col s12" method="post" action="create-interest">
                        <div class="row">
                            <div class="input-field col s12">
                                <select name="type-interest">
                                    <?php
                                        _::each($typesInterest, function($typeInterest){
                                            ?>
                                            <option value="<?= $typeInterest ?>"><?= $typeInterest ?></option>
                                            <?php
                                        });
                                    ?>
                                </select>
                                <label>Tipo de interés</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input id="value" type="text" name="value">
                                <label for="value">Valor</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <textarea id="description" class="materialize-textarea" name="description"></textarea>
                                <label for="description" >Descripción</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <button class="btn cyan waves-effect waves-light right" type="submit"> Registrar
                                    <i class="mdi-content-send right"></i>
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            
        </div>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->