<!DOCTYPE html>
<html lang="es">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
        <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
        <title><?= $this->pageTitle ?></title>
        <!-- Favicons-->
        <link rel="icon" href="/resources/image/favicon/favicon-32x32.png" sizes="32x32">
        <!-- Favicons-->
        <link rel="apple-touch-icon-precomposed" href="/resources/image/favicon/apple-touch-icon-152x152.png">
        <!-- For iPhone -->
        <meta name="msapplication-TileColor" content="#00bcd4">
        <meta name="msapplication-TileImage" content="/resources/image/favicon/mstile-144x144.png">
        <!-- For Windows Phone -->
        <!-- CORE CSS-->
        <link href="/css/materialize.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="/css/style.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- Custome CSS-->    
        <link href="/css/custom/custom.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
        <link href="/js/vendor/plugins/prism/prism.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="/js/vendor/plugins/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet" media="screen,projection">
        <link href="/js/vendor/plugins/chartist-js/chartist.min.css" type="text/css" rel="stylesheet" media="screen,projection">
        <!-- jQuery Library -->
        <script type="text/javascript" src="/js/vendor/plugins/jquery-1.11.2.min.js"></script>    
    </head>
    <body>
        <!-- Start Page Loading -->
<!--        <div id="loader-wrapper">
            <div id="loader"></div>        
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>
        </div>-->
        <!-- End Page Loading -->
        
        <!-- //////////////////////////////////////////////////////////////////////////// -->
        
        <?= $this->partial(__PATH__ . "/app/view/partials/header.phtml"); ?>
        <!-- START MAIN -->
        <div id="main">
            <!-- START WRAPPER -->
            <div class="wrapper">
                <?= $this->partial(__PATH__ . "/app/view/partials/left-sidebar.phtml"); ?>
                <?= $this->yieldView(); ?>
            </div>
            <!-- END WRAPPER -->
        </div>
        <!-- END MAIN -->
        <?= $this->partial(__PATH__ . "/app/view/partials/footer.phtml"); ?>

        <!-- //////////////////////////////////////////////////////////////////////////// -->
        
        <!-- ================================================
        Scripts
        ================================================ -->
        
        <!--materialize js-->
        <script type="text/javascript" src="/js/vendor/materialize.min.js"></script>
        <!--prism-->
        <script type="text/javascript" src="/js/vendor/plugins/prism/prism.js"></script>
        <!--scrollbar-->
        <script type="text/javascript" src="/js/vendor/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
        <!-- chartist -->
        <script type="text/javascript" src="/js/vendor/plugins/chartist-js/chartist.min.js"></script>   
        <!--plugins.js - Some Specific JS codes for Plugin Settings-->
        <script type="text/javascript" src="/js/vendor/plugins.min.js"></script>
        <!--custom-script.js - Add your own theme custom JS-->
        <script type="text/javascript" src="/js/vendor/custom-script.js"></script>
        <!--main.js - Add your own theme custom JS-->
        <script type="text/javascript" src="/js/main.js"></script>
    </body>
</html>